name: Port Request Labeler

on:
  pull_request:
    branches:
      - release/**

jobs:
  release_labeler:
    name: Release labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./build/actions/AutoLabel
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          label: "Port Request"
