name: TSLint Enforcement
on: [pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: TSLint
        uses: aaomidi/gh-action-tslint@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tslint_config: 'tslint-sql.json'
